### ISSUE TITLE
sketching on liqpostcard is a bit broken

### ISSUE THREAD

**Issue by rburchell** [lcuk/liqbase-playground#1]
The newly added splash screen to liqsketchedit never goes away when editing a postcard sketch, making it impossible to see what you are drawing without exiting the editor (inconvenient/bad).

**Comment by lcuk** [comment]
fixed in libliqbase
http://github.com/lcuk/libliqbase/commit/d3920198103d6e35f3c020f8901ea4c28d4d5200

**Comment by lcuk** [comment]
.
